### ISSUE TITLE
Unable to import ContentKeyPolicy Containing FairPlay DRM configuration

### ISSUE THREAD

**Issue by ben-voytko-talogy** [mediakind-video/ams-migration-tool#14]
I was unable to migrate any content key policy that contained FairPlay DRM using the ams-migration-tool. It appears that the export is missing data. Ask shows as null, but I also see no reference to certificate or certificate password in export file. 

Mostly 400 errors like this 
`RESPONSE 400: 400 Bad Request;ERROR CODE: 1000.2000.2000.1040;{\n  \"error\": {\n    \"code\": \"1000.2000.2000.1040\",\n    \"detail\": \"Failed to process payload. Missing required field: ContentKeyPolicyFairPlayConfiguration.fairPlayPfx\"\n  },\n  \"ref\": \"ef75e747-1878-4e06-98f5-64d11b087e93\",\n  \"status\": 400\n}\n;"`

**Comment by luke-jacob-mk** [comment]
The main branch has been updated to include pulling FairPlay secrets with the ContentKeyPolicies. It should work as expected now.

**Comment by ben-voytko-talogy** [comment]
Confirmed I was able to import content key policies containing a fairplay configuration!
