### ISSUE TITLE
streaming endpoint load failed for west europe

### ISSUE THREAD

**Issue by sjorsmiltenburg** [mediakind-video/ams-migration-tool#24]
error msg="unable to import streamingEndpoint default: PUT https://api.mk.io/api/ams/mkiovideostreamer/streamingEndpoints/default;RESPONSE 400: 400 Bad Request;ERROR CODE: 1000.2000.3500.1030;{\n  \"error\": {\n    \"code\": \"1000.2000.3500.1030\",\n    \"detail\": \"Streaming Endpoint load failed. Your subscription is in 'westeurope' but you've requested a streaming endpoint in 'West Europe'. Streaming endpoints must be located within the same location as the subscription.\"\n  },\n  \"ref\": \"9e1820d0-a83d-46bf-bc33-9e5de2dfc56c\",\n  \"status\": 400\n}\n;"
time="2024-05-16T15:32:10+02:00" level=info msg="Skipped 0 existing streamingEndpoints"
time="2024-05-16T15:32:10+02:00" level=info msg="Imported 0 streamingEndpoints"
time="2024-05-16T15:32:10+02:00" level=error msg="error importing streaming endpoints: failed to import 1 StreamingEndpoints: [default]"

it looks like it can't match 'westeurope' to 'West Europe' somehow

**Comment by bugMaker-237** [comment]
Created a pull request for that: #26

**Comment by luke-jacob-mk** [comment]
PR has been merged. Closing.
